name: vilhelmprytz-curl
base: core18
version: '7.73.0'
summary: command line tool and library for transferring data with URLs
description: |
  command line tool and library
  for transferring data with URLs
  (since 1998)

grade: stable
confinement: strict

parts:
  curl:
    plugin: make
    source: https://curl.se/download/curl-7.73.0.tar.gz
    build-packages:
      - libssl-dev
    override-build: |
      ./configure --with-ssl
      snapcraftctl build

apps:
  curl:
    command: usr/local/bin/curl
    plugs:
      - network
